
import os
import json
import re
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).parent.parent.parent
CONFIG_DIR = ROOT_DIR / "config" / "categories"
PROMPTS_FILE = ROOT_DIR / "assets" / "icons" / "PROMPTS.md"

# Neon Colors per Category
CATEGORY_COLORS = {
    "3D": "Lime",
    "AI": "Cyan",
    "Audio": "Orange",
    "Clipboard": "Azure",
    "Document": "Blue",
    "Image": "Magenta",
    "System": "Azure",
    "Tools": "Red",
    "Sequence": "Violet",
    "Video": "Purple",
    "Comfyui": "Cyan",
    "ComfyUI": "Cyan"
}

def load_existing_prompts():
    prompts = {}
    if not PROMPTS_FILE.exists():
        return prompts
    
    with open(PROMPTS_FILE, "r", encoding="utf-8") as f:
        lines = f.readlines()
        
    for line in lines:
        if line.strip().startswith("|") and not line.strip().startswith("| :"):
            parts = [p.strip() for p in line.strip().split("|")]
            if len(parts) >= 4:
                # parts[0] is empty, parts[1] is icon_id, parts[2] is prompt, parts[3] is category
                icon_id = parts[1].strip("`")
                if icon_id == "Icon ID": continue
                prompt = parts[2]
                category = parts[3]
                prompts[icon_id] = {"prompt": prompt, "category": category}
    return prompts

def _normalize_items(data):
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        if isinstance(data.get("features"), list):
            return data["features"]
        return [data]
    return []

def scan_configs():
    icons = {}
    for json_file in CONFIG_DIR.glob("*.json"):
        with open(json_file, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                items = _normalize_items(data)
                for item in items:
                    if "icon" in item:
                        icon_path = item["icon"]
                        icon_name = os.path.basename(icon_path)
                        category = item.get("category", data.get("category", "System") if isinstance(data, dict) else "System")
                        icons[icon_name] = {
                            "category": category,
                            "name": item.get("name", "")
                        }
            except Exception as e:
                print(f"Error reading {json_file}: {e}")
    return icons

def main():
    existing_prompts = load_existing_prompts()
    current_icons = scan_configs()
    
    print(f"Found {len(current_icons)} icons in config.")
    
    new_prompts = {}
    
    # Process all current icons
    for icon_name, info in current_icons.items():
        category = info["category"]
        
        # Keep existing prompt if available
        icon_key = icon_name.lower()
        if icon_name in existing_prompts:
            prompt = existing_prompts[icon_name]["prompt"]
            # Update category if changed
            # But keep custom prompt
        else:
            # Generate new prompt
            color = CATEGORY_COLORS.get(category, "White")
            # Special case for AI Text Refine
            if "refine" in icon_key or "grammar" in icon_key or "text_lab" in icon_key:
                color = "Blue/Purple"
                desc = "Crystal pen writing on floating digital glass interface"
                prompt = f"{desc}. Neon {color} Glow. Translucent Soft Glass."
            else:
                desc = "Abstract geometric symbol"
                prompt = f"{desc}. Neon {color} Glow. Translucent Soft Glass."
                
        new_prompts[icon_name] = {
            "prompt": prompt,
            "category": category
        }

    # Add ContextUp.ico manually if not in config
    if "ContextUp.ico" not in new_prompts:
        new_prompts["ContextUp.ico"] = {
            "prompt": "Wooden arrow pointing upward, encased in translucent soft glass with subtle neon blue accents. Main application logo.",
            "category": "System"
        }
        if "ContextUp.ico" in existing_prompts:
             new_prompts["ContextUp.ico"]["prompt"] = existing_prompts["ContextUp.ico"]["prompt"]

    # Sort by Category then Icon Name
    sorted_items = sorted(new_prompts.items(), key=lambda x: (x[1]["category"], x[0]))
    
    # Write MD
    with open(PROMPTS_FILE, "w", encoding="utf-8") as f:
        f.write("# 🎨 Icon Prompts\n\n")
        f.write("Auto-generated by `dev/scripts/update_prompts_md.py`.\n\n")
        f.write("| Icon ID | Prompt | Category |\n")
        f.write("| :--- | :--- | :--- |\n")
        
        for icon_name, info in sorted_items:
            f.write(f"| `{icon_name}` | {info['prompt']} | {info['category']} |\n")
            
    print(f"Updated {PROMPTS_FILE}")

if __name__ == "__main__":
    main()
